model:
    name: two_view_pipeline
    extractor:
        name: extractors.superpoint_open
        max_num_keypoints: 2048
        detection_threshold: 0.005
        nms_radius: 4
    matcher:
        name: gluefactory_nonfree.superglue
benchmarks:
    hpatches:
        eval:
            estimator: opencv
            ransac_th: 0.5
        model:
            extractor:
                max_num_keypoints: 1024
